export const studentsMock = [
  {
    id: 1,
    idade: 20,
    email: "ana.souza@email.com",
    curso: "Ciência da Computação",
    matriculado: true,
    endereco: {
      rua: "Rua das Flores, 123",
      cidade: "São Paulo",
      estado: "SP",
    },
    disciplinas: ["Algoritmos", "Estrutura de Dados", "Banco de Dados"],
  },
  {
    id: 2,
    nome: "Bruno Oliveira",
    idade: 22,
    email: "bruno.oliveira@email.com",
    curso: "Sistemas de Informação",
    matriculado: false,
    endereco: {
      rua: "Av. Brasil, 456",
      cidade: "Belo Horizonte",
      estado: "MG",
    },
    disciplinas: ["Redes de Computadores", "Engenharia de Software"],
  },
  {
    id: 3,
    nome: "Camila Ferreira",
    idade: 19,
    email: "camila.ferreira@email.com",
    curso: "Matemática",
    matriculado: true,
    endereco: {
      rua: "Rua da Universidade, 789",
      cidade: "Campinas",
      estado: "SP",
    },
    disciplinas: ["Cálculo I", "Estatística", "Álgebra Linear"],
  },
  {
    id: 4,
    nome: "Diego Lima",
    idade: 21,
    email: "diego.lima@email.com",
    curso: "Engenharia de Software",
    matriculado: true,
    endereco: {
      rua: "Rua do Estudante, 321",
      cidade: "Curitiba",
      estado: "PR",
    },
    disciplinas: ["Programação Orientada a Objetos", "Sistemas Operacionais"],
  },
  {
    id: 5,
    nome: "Eduarda Mendes",
    idade: 23,
    email: "eduarda.mendes@email.com",
    curso: "Análise e Desenvolvimento de Sistemas",
    matriculado: false,
    endereco: {
      rua: "Av. Central, 654",
      cidade: "Recife",
      estado: "PE",
    },
    disciplinas: ["Desenvolvimento Web", "UX/UI Design"],
  },
];
